In [2]:
import numpy as np


# Arrary indexing

## one-dimension

In [23]:
x = np.arange(10)
#print(x1)

In [24]:
x[:5]

array([0, 1, 2, 3, 4])

In [25]:
x[5:]

array([5, 6, 7, 8, 9])

In [26]:
x[4:7]

array([4, 5, 6])

In [27]:
x[::2]

array([0, 2, 4, 6, 8])

In [28]:
x[1::2]

array([1, 3, 5, 7, 9])

## Multi-dimension

In [42]:
x2 = np.array([[3, 5, 2, 4],
               [7, 6, 8, 8],
               [1, 6, 7, 7]])

In [38]:
x2[0, 0]

3

In [39]:
x2[2, 0]

1

In [40]:
x2[:2, :3]

array([[3, 5, 2],
       [7, 6, 8]])

In [41]:
x2[:3, ::2]

array([[3, 2],
       [7, 8],
       [1, 7]])

## Be careful due to Numpy data is reference type 

In [43]:
print(x2)

[[3 5 2 4]
 [7 6 8 8]
 [1 6 7 7]]


In [46]:
x2_sub = x2[:2, :2]
print(x2_sub)

[[3 5]
 [7 6]]


In [48]:
x2_sub[0, 0] = 99
print(x2_sub)

[[99  5]
 [ 7  6]]


In [49]:
print(x2)

[[99  5  2  4]
 [ 7  6  8  8]
 [ 1  6  7  7]]


## Creating copies of arrays

In [50]:
x2_sub_copy = x2[:2, :2].copy()
print(x2_sub_copy)

[[99  5]
 [ 7  6]]


In [51]:
x2_sub_copy[0, 0] = 42
print(x2_sub_copy)

[[42  5]
 [ 7  6]]


In [52]:
print(x2)

[[99  5  2  4]
 [ 7  6  8  8]
 [ 1  6  7  7]]


# Reshaping of Arrays

In [53]:
grid = np.arange(1, 10).reshape((3, 3))
print(grid)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [55]:
x = np.array([1, 2, 3])
x.reshape((1, 3))

array([[1, 2, 3]])

In [56]:
x.reshape((3, 1))

array([[1],
       [2],
       [3]])

# Boolean Arrays as Masks

In [57]:
x = np.array([[5, 0, 3, 3],
            [7, 9, 3, 5],
            [2, 4, 7, 6]])

In [58]:
x < 5

array([[False,  True,  True,  True],
       [False, False,  True, False],
       [ True,  True, False, False]])

In [59]:
x[x < 5]

array([0, 3, 3, 3, 2, 4])

## Counting entries

In [60]:
np.count_nonzero(x < 6)

8

In [61]:
np.sum(x < 6)

8

In [62]:
#how many values less than 6 in each row
np.sum(x < 6, axis = 1)

array([4, 2, 2])

In [63]:
# are all values less than 10
np.all(x < 10)

True

In [64]:
# are there any values less than zeros?
np.any(x < 0)

False

In [65]:
# are all values in each row less than 8?
np.all(x < 8, axis = 1)

array([ True, False,  True])